---
language: php
dist: trusty
group: edge
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - hhvm-3.12
  - hhvm-3.15
  - hhvm-3.18
  - hhvm-3.21
  - hhvm-3.24
  - hhvm-3.27
  - hhvm-3.30

matrix:
  allow_failures:
    - php: nightly
    - php: master

  include:
    - php: 8.0
      - dist: focal
        addons:
          apt:
            packages:
              - "libonig5"

    - php: 8.1
      - dist: focal
        addons:
          apt:
            packages:
              - "libonig5"

    - php: 8.2
      - dist: focal
        addons:
          apt:
            packages:
              - "libonig5"

    - php: 8.3
      - dist: focal
        addons:
          apt:
            packages:
              - "libonig5"

    - php: master
      - dist: focal
        addons:
          apt:
            packages:
              - "libonig5"

    - php: nightly
      - dist: focal
        addons:
          apt:
            packages:
              - "libonig5"

script: "php test/cli.php"
